### ISSUE TITLE
sort_url not implemented in setup guide in readme

### ISSUE THREAD

**Issue by brianHamill** [plumdog/flask_table#99] opened 2018-03-08 18:02 UTC
When following the setup in the readme I receive the warning that not all abstract methods have been implemented, it seems the `sort_url` method has been left out of the readme.

Possibly consider adding this to the readme?

**Comment by plumdog** [comment] 2018-03-08 19:08
Hi!

You shouldn't get it complaining about `sort_url` unless you set `allow_sort = True` on the table class (it defaults to false). If you do set `allow_sort = True`, then you'll get `NotImplementedError: sort_url not implemented` when you instantiate the table. You then need to implement this to tell the table what url to use for each header.

As for what is in the readme: there is [a section for it](https://github.com/plumdog/flask_table/blob/master/README.md#sortable-tables) which I think has main info in. If there's anything you think it might be worth adding, let me know.

**Comment by plumdog** [comment] 2018-04-12 07:31
I'm increasingly confident that the cause of this is PyCharm/other IDE being opinionated about unimplemented methods, rather than a problem with `flask_table`.

I'll close this for now, but if you can let me know what it was (IDE/linter?) that was generating the warning, I'll look at why and see if there's something sensible to change.

**Closed by plumdog** 2018-04-12 07:31 UTC
